[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
test = 'test'
cache_path  = 'cache_foundry'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config